# SITE CONFIGURATION
baseurl: "" # Set it to "" if use for personal site. The subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
imageurl: "https://source.unsplash.com/category/nature/2600x500" #"https://unsplash.it/2600/500?random"


# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Bluefish
  #avatar: avatar.png
  hometitle: 首页 #display on navigation menu.
  yoursitetitle: Bluefish
  gravatar: # Email MD5 hash
  description: "used by search engines" # used by search engines
  visiblewords: 100
  # Header and footer text
  header_text: >
     

  header_text_feature_image: img/sample_feature_img.png
  place_holder_image: img/sample_feature_img.png
  footer_text: >
   <a href="https://AIBluefisher.github.io">AIBluefisher</a>

  # Icons
  rss: false
  email_address: "RainnyChen@outlook.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "AIBluefisher"
  weibo:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  #str_next: "Next"
  #str_prev: "Prev"
  str_continue_reading: "继续阅读"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
enforce_ssl: "AIBluefisher.github.io"
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/

# Posted in ... with ...
sechby:
  category:   #in
  tag:   #with

# BUILD SETTINGS
markdown: redcarpet
#highlighter: pygments
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-paginate
